<% dockerInfo = new groovy.json.JsonSlurper().parse(dockerInfoFile) %>
FROM buildpack-deps:${(dockerInfo.architecture=='s390x')?'xenial':'trusty'}-curl

ENV DEBIAN_FRONTEND noninteractive

# Initial update and some basics.
RUN apt-get update && apt-get install -y imagemagick && apt-get install -y unzip

ADD . /nodejsAction
